### ISSUE TITLE
does not supporting Persian text(unicode not supported)

### ISSUE THREAD

**Issue by davidjonz2005** [NathanaelA/nativescript-zxing#11]
Hi @NathanaelA  
i created a qrcode and my text is Persian but i see just a string of ? when decoding in my phone. 
do i need to add something to my code to support Persian?

**Comment by davidjonz2005** [comment]
thanks to [this link](https://stackoverflow.com/questions/9835774/how-do-i-encode-characters-using-utf-8-in-a-qr-code-using-zxing-project) i just add this lines to your code and everything solved 

 
add it to zxing.android.js
at line 39 clean

>  var hints = null;

and put
```
var hints = new java.util.Hashtable();
    var characterset = com.google.zxing.EncodeHintType.CHARACTER_SET;
    hints.put(characterset, "utf-8");
``` 

instead
for ios currently i dont know maybe @NathanaelA helps.

**Comment by kalininskiy** [comment]
same problem with Cyrillic fonts
@NathanaelA please add hints solution with UTF-8 to project

**Comment by NathanaelA** [comment]
The pull request was accepted and the latest version on NPM has this change...
