### ISSUE TITLE
buildMetadata fails when combined with nativescript-barcodescanner

### ISSUE THREAD

**Issue by dartmann** [NathanaelA/nativescript-zxing#12]
When I combine this plugin in a project with EddyVerbruggen's [nativescript-barcodescanner plugin](https://github.com/EddyVerbruggen/nativescript-barcodescanner) the compilation step buildMetadata failes with the following stacktrace:

`Exception in thread "main" java.lang.IllegalArgumentException: Class com.google.zxing.pdf417.PDF417ResultMetadata conflict: /Users/david/WebstormProjects/qr-test/platforms/android/build/intermediates/exploded-aar/barcodescanner-release-2.1.6/jars/classes.jar and /Users/david/.gradle/caches/modules-2/files-2.1/com.google.zxing/core/3.2.1/2287494d4f5f9f3a9a2bb6980e3f32053721b315/core-3.2.1.jar
	at com.telerik.metadata.ClassRepo.addToCache(ClassRepo.java:21)
	at com.telerik.metadata.Builder.build(Builder.java:38)
	at com.telerik.metadata.Generator.main(Generator.java:44)`

I tried to remove the node_modules folder followed by `npm clear cache` and also removed and added the platform. But nothing helped.

**Comment by NathanaelA** [comment]
Yep, this is a known issue -- see #4 and #10 for solutions.
I'm updating the docs so that the issue and solution is in it.
