### ISSUE TITLE
Conflict into builder for Android

### ISSUE THREAD

**Issue by EduhCosta** [NathanaelA/nativescript-zxing#13]
I'm execute "tns run android" and my app no compiler, but for IOS no exist this problem.
Help-me please!!

![captura de tela 2017-09-04 as 15 49 04](https://user-images.githubusercontent.com/16820917/30036329-ab75c9a8-9188-11e7-91a6-d52e6af067f1.png)

**Comment by NathanaelA** [comment]
Please see the notes at the bottom of the readme on this repo.   Or issues #12 , #4
