### ISSUE TITLE
Adding newline within encode data

### ISSUE THREAD

**Issue by kwong93** [NathanaelA/nativescript-zxing#15]
`var stringToEncode = "First string" + "\n" + Second String";`

when passing to `createBarcode`
```
var zx = new ZXing();
var barcode = zx.createBarcode({encode: stringToEncode, height: 30, width: 400, format: ZXing.CODE_128});
```
I get:

```
JS: Error: java.lang.IllegalArgumentException: Bad character in input:
JS:     com.google.zxing.oned.Code128Writer.encode(Code128Writer.java:83)
```
I've tried several ways to input a newline:
`String.charCodeAt(10)`
`String.charCodeAt(13)`
`"\r\n"`
`"\r"`
 but same error, how do I add a new line to the encode data?

Looking at the src code for CodeWriter it seems the char code for the new line input is greater than 127 but why?

https://github.com/zxing/zxing/blob/master/core/src/main/java/com/google/zxing/oned/Code128Writer.java

**Comment by NathanaelA** [comment]
Well based on the https://en.wikipedia.org/wiki/Code_128 the only code-128 that supported the CR or LF character is Code-128A.   If you are using Code_128A character set; you CANNOT use lowercase letters; so you basically need to tell it to do the 128A character set; and make sure that all your characters are available in the 128a character set...

**Comment by kwong93** [comment]
Zxing doesn't seem to provide a way to force 128A. I thought the 128 spec covers all 128 characters, so why would we need to specify the specific set? I tried a string with mix of numbers and upper/lower case and they worked, just not the new line.

**Comment by NathanaelA** [comment]
I'm not sure I was real clear -- you need to pass in the code for Code 128A - then pass in the code for CR; it isn't a "13" or "10"
So Switch to Code A = 101; then CR = 77.

**Comment by kwong93** [comment]
Could you post an example of a string using those codes?

**Comment by kwong93** [comment]
@NathanaelA I found the problem, zxing had an issue where it could not encode certain ascii characters before version 3.3.1, and newline was one of them. See https://github.com/zxing/zxing/issues/649

The native android lib https://github.com/journeyapps/zxing-android-embedded will also have this problem as it hasn't been updated since the 3.3.1 release.

I updated the zxing core lib to 3.3.1 in include.gradle, I don't know why the android-core cannot resolve to 3.3.1 and higher though.

```
dependencies {
	compile 'com.google.zxing:android-core:3.3.0'
	compile 'com.google.zxing:core:3.3.1'	
}
```

Full example below of working encode of new line:

```
var ZXing = require('nativescript-zxing');

var zx = new ZXing();
var thestring  = "CAT" + "\n" + "DOG";
var barcodeBitmap = zx.createBarcode({encode: thestring, height: 30, width: 400, format:ZXing.CODE_128});

```

**Comment by NathanaelA** [comment]
Awesome thanks for finding out the library had the issues; I'll get a update pushed...

**Comment by corebreaker** [comment]
And so, how to solve the problem ?

**Comment by NathanaelA** [comment]
@corebreaker 
```
var ZXing = require('nativescript-zxing');

var zx = new ZXing();
var thestring  = "CAT" + "\n" + "DOG";
var barcodeBitmap = zx.createBarcode({encode: thestring, height: 30, width: 400, format:ZXing.CODE_128});
```

The "\n" is a newline...
