### ISSUE TITLE
iOS compilation problem

### ISSUE THREAD

**Issue by racknoris** [NathanaelA/nativescript-zxing#21]
I'm using NS 4.2,
when I tried to `tns run ios`, I got:

```
[!] CocoaPods could not find compatible versions for pod "ZXingObjC":
  In Podfile:
    ZXingObjC (~> 3.4.0)
None of your spec sources contain a spec satisfying the dependency: `ZXingObjC (~> 3.4.0)`.
You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

Unable to apply changes on device: C38BB9EB-3CA4-4AF9-9406-C641185DD5B8. Error is: Command pod failed with exit code 31.
```

So I tried to manually change the Podfile so it'll use the latest pod version (3.6.1), but it gave me the same error. I also tried to remove the `platform :ios, '8.0'` line, and it didn't work as well.

What I eventually did was to downgrade to `nativescript-zxing@1.5.5`, and it now works

**Comment by NathanaelA** [comment]
Yeah, you need to do a `pod repo update` other wise your cocoapods are out of date and won't show newer versions of any cocoapods.
