### ISSUE TITLE
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'BarcodeFormat' of undefined TypeError: Cannot read property 'BarcodeFormat' of undefined

### ISSUE THREAD

**Issue by moorateeahtashil** [NathanaelA/nativescript-zxing#25]
var zx = new ZXing();
                    var img = zx.createBarcode({encode: "text", height: 500, width: 500, format: ZXing.QR_CODE});
                    imgbar.imageSource = <ImageSource> fromNativeSource(img);

This code renders this error. Any default in the code

**Comment by NathanaelA** [comment]
See demo: https://github.com/NathanaelA/nativescript-zxing/blob/master/demo/app/main-page.js#L99
Your code should be: `zx.QR_CODE` not `ZXing.QR_CODE`
