### ISSUE TITLE
TypeError: Cannot read property 'zxing' of undefined qrcode

### ISSUE THREAD

**Issue by mathosmor** [NathanaelA/nativescript-zxing#26]
Hello, I saw the demo and a was try do in my project but everytime I try execut my aplication this error show for me. My code is that: 

`var ZXing = require('nativescript-zxing');
var imageSource = require('image-source');
var fs = require('file-system');
var utils = require('utils/utils');

var img, txt, page;
exports.pageLoaded = function(args) {
	page = args.object;
	img = page.getElementById('img');
	txt = page.getElementById('txt');
};

exports.encode = function() {
	console.log('RECEBEU')
	var text = txt.text || "Demo by Master Technology";
	var newImg = ZXing.prototype.createBarcode({encode: text, height: 500, width: 500,});

	img.imageSource = imageSource.fromNativeSource(newImg);
	var save = getElementById('save');
	save.isEnabled = true;`

**Comment by NathanaelA** [comment]
You need to do a `tns platform clean android` and/or `tns platform clean ios`.    Sometimes tns doesn't realize it needs to rebuild the app so it doesn't compile in the native code that is needed.

**Comment by mathosmor** [comment]
Oo thanks NathanaeI, that´s work for me :D
