### ISSUE TITLE
Android return empty image

### ISSUE THREAD

**Issue by cherimo** [NathanaelA/nativescript-zxing#29]
Hey,

Is it possible to make it run also on android?

I am using:
Nativescript 6.0.2
Android 9.0
Angular

The iOS version works like a charm but within android It gives me an empty image.
Also it doesn't give me any error or something like that.

I am using the following code to generate within my angular project:
`  ...
        const barcodeImage = this.page.getViewById<Image>("qr-"+index);
        const zx = new ZXing();
        const newImg = zx.createBarcode({
            encode: qrCode,
            height: 200, 
            width: 200,
            format: ZXing.QR_CODE
        });
        barcodeImage.imageSource = imgSource.fromNativeSource(newImg);
...`

The HTML
`       <Image style="margin-top:0;" id="qr-{{item.index}}" height="200" width="200" stretch="aspectFill" ></Image>`

Am I doing something wrong here?

Thanks in advance.

**Comment by NathanaelA** [comment]
@cherimo - The https://npm.proplugins.org/-/web/detail/@proplugins/nativescript-zxing is the maintained version and has been tested on NS6.     See https://proplugins.org for more info.

**Comment by cherimo** [comment]
@NathanaelA thx for your quick reply, as for the new repository when I am trying to install the new plugin I get an 404 error in my console.
When i am trying to download it manualy I get also an 404 page as of the plugin doesnt exist any more.

**Comment by NathanaelA** [comment]
The plugins should exist if you have logged into the server.   I just tested and it worked fine.

**Comment by cherimo** [comment]
So I followed the instructions within: https://npm.proplugins.org/-/web/detail/@proplugins/nativescript-zxing

I used the following command: tns plugin add @proplugins/nativescript-zxing

This is what I get:

`0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '@proplugins/nativescript-zxing',
1 verbose cli   '--save' ]
2 info using npm@6.9.0
3 info using node@v10.16.1
4 verbose npm-session f05ba34c13f2384c
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 https://registry.npmjs.org/@proplugins%2fnativescript-zxing 1070ms
8 http fetch GET 404 https://registry.npmjs.org/@proplugins%2fnativescript-zxing 397ms
9 silly fetchPackageMetaData error for @proplugins/nativescript-zxing@latest 404 Not Found - GET https://registry.npmjs.org/@proplugins%2fnativescript-zxing - Not found
10 timing stage:rollbackFailedOptional Completed in 1ms
11 timing stage:runTopLevelLifecycles Completed in 2548ms
12 verbose stack Error: 404 Not Found - GET https://registry.npmjs.org/@proplugins%2fnativescript-zxing - Not found
12 verbose stack     at res.buffer.catch.then.body (/usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:104:15)
12 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
13 verbose statusCode 404
14 verbose pkgid @proplugins/nativescript-zxing@latest
15 verbose cwd /Users/Dev/Desktop/txxlApp
16 verbose Darwin 18.7.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "@proplugins/nativescript-zxing" "--save"
18 verbose node v10.16.1
19 verbose npm  v6.9.0
20 error code E404
21 error 404 Not Found - GET https://registry.npmjs.org/@proplugins%2fnativescript-zxing - Not found
22 error 404
23 error 404 '@proplugins/nativescript-zxing@latest' is not in the npm registry.
24 error 404 You should bug the author to publish it (or use the name yourself!)
25 error 404 Note that you can also install from a
26 error 404 tarball, folder, http url, or git url.
27 verbose exit [ 1, true ]
`

Even when I try to visit the source page: https://git.proplugins.org/proplugins/nativescript-zxing it gives me 404 not found page.

Am I missing something?

**Comment by NathanaelA** [comment]
As for NPM; according to the log you are trying to get the plugins from `https://registry.npmjs.org/@proplugins%2fnativescript-zxing`  **this is NOT the correct server**.   You have to have logged into the proplugins npm server via the `npm login` command at least once -- which will then associate the @proplugins with the proplugins npm server.   It is a totally different npm server.   The `registry.npmjs.org` has no knowledge of the @proplugins namespace.    

![image](https://user-images.githubusercontent.com/850871/63124990-305ba480-bf72-11e9-83d5-e7e09023f21e.png)
The (I) in the upper right hand corner should display what this image displays.    That is the proper login command (which you can just copy and paste to your console from the proplugins site).   However, you do need a valid proplugins subscription for it to work...

Also for the git.proplugins.org; you have to logged into the git server with an account that has a subscription so that it has access to that namespace and then you will see:
![image](https://user-images.githubusercontent.com/850871/63124718-8e3bbc80-bf71-11e9-85e9-5b1e19b6a55b.png)

**Comment by cherimo** [comment]
@NathanaelA thx I have added the proplugin server, i can see the QR that has been generated within Android.

Do you have an idea maybe why it isn't working when I am using the nativescroll pager?
I want to generate an QR every time someone scrolls. It gives me:
Cannot set property 'imageSource' of undefined 
While on iOs everything works fine.

For every slide that is being called:
     
```
 setTimeout(() => {
        const barcodeImage = this.page.getViewById<Image>("qr-"+index);   
        const zx = new ZXing();
        const newImg = zx.createBarcode({
            encode: qrCode,
            height: 200, 
            width: 200,
            format: ZXing.QR_CODE
        });
        barcodeImage.imageSource = imgSource.fromNativeSource(newImg);
 }, 500);
```

And the template is:
```
       <Pager style="margin-top:10;" row="1" [items]="items | async" [itemTemplateSelector]="templateSelector" #pager [selectedIndex]="currentPagerIndex" (selectedIndexChange)="onIndexChanged($event)" class="pager" backgroundColor="transparent">

            <ng-template pagerTemplateKey="example" let-i="index" let-item="item">
                <GridLayout class="pager-item" rows="auto,auto,*" columns="*">

                            <Image style="margin-top:10;margin-bottom:10;" id="qr-{{item.index}}" height="150" width="200" stretch="aspectFill" class="text-center"></Image>
    
                </GridLayout>
            </ng-template>
</Pager>

```

If you have an idea that will help me further, much appreciated.

Thank you very much for all your time and effort so far.

**Comment by NathanaelA** [comment]
Hmm, that should work -- that is basically very close to what my demo does.    Any chance you can provide me a simple angular demo that is broken and I can take a look at it.   Maybe their is something in the angular side that is messing things up.

**Comment by cherimo** [comment]
@NathanaelA again thx for you quick reply, I tested some other(carousel/slider) plugins and it seems that your plugin works like a charm.
I don't get any errors, so it has to do something with the pager plugin, its creating another window/frame where binding data is not that easy.
Thx for your help and for proplugins suggestion, nice community.
