### ISSUE TITLE
Deprecated Nativescript plugin

### ISSUE THREAD

**Issue by pvcoelho** [NathanaelA/nativescript-zxing#30]
Any substitute for this deprecated Nativescript plugin?
I have several apps that need to display a barcode and currently there is no solution for Nativescript 7 which is the only working version for the new iOS.

**Comment by NathanaelA** [comment]
This should work fine with NS7.

**Comment by NathanaelA** [comment]
The supported @proplugins/nativescript-zxing should be working fine.

**Comment by pvcoelho** [comment]
Hi @NathanaelA ,
I've tried to install the @proplugins/nativescript-zxing plugin but without any success. Apparently doesn't exist in the npm repository:
![imagem](https://user-images.githubusercontent.com/35145153/99795579-e6258380-2b23-11eb-8269-90707a51caf3.png)

**Comment by NathanaelA** [comment]
You have to have a ProPlugins subscription to get access to anything @proplugins.   https://proplugins.org for more info.
