### ISSUE TITLE
Demo site not found

### ISSUE THREAD

**Issue by simba4everyoung** [NathanaelA/nativescript-zxing#7]
Hi~ 
I tried to use your plugin for a project. 
But the [demo site](http://github.com/NathanaelA/nativescript-zxing/demo) returns 404. 
Would you mind look into it? Thanks!

**Comment by NathanaelA** [comment]
Sorry, the link is invalid; I have updated the readme and the link to the source is here:
https://github.com/NathanaelA/nativescript-zxing/tree/master/demo

**Comment by simba4everyoung** [comment]
Thanks for the update!
